- name: app setup
  include_roles:
    name: common
    tasks_from: app-setup

- name: python setup
  include_roles:
    name: common
    tasks_from: python 


- name: systemd setup
  include_roles:
    name: common
    tasks_from: systemd